### ISSUE TITLE
Backup failed and get stuck

### ISSUE THREAD

**Issue by mccaan** [FTBTeam/FTB-Backups#21]
With the latests version of FTB Backups, backups are always failing.

Automatic Backup is not done and when I try to get a manual backup get folowing message

[19:11:26] [Server thread/INFO] [FTB Utilities Backups/]: Server Backup started!
[19:11:26] [Server thread/INFO] [FTB Utilities Backups/]: World saving failed!

But no more log files not in latest.log nor debug.log

Tried changing the backup directory, but with no sucess

**Comment by FakeLook** [comment]
happens to me too. I am running version 2.0.0.11. Stopped backing up after I changed compression to 0, reducing max backup folder size to "5 Gb" and reducing backup interval to 20.

**Comment by ToMe25** [comment]
I am having the same Issue except it does try automatic backups, they just fail with the same message as the manual ones.
Also it only creates the error message saying "World saving failed!" once, and after that it always says backup in progress.
I am using version 2.0.0.11 for minecraft 1.14.4 with the default config settings.

**Comment by Quest79** [comment]
Still not working. No logs. World Backup Failed. Pretty alpha quality stuff right now.
