### ISSUE TITLE
Backup stuck when no one is on the server.

### ISSUE THREAD

**Issue by Leassus** [FTBTeam/FTB-Backups#23]
Backups seems to be stuck when none is on the server.
Most of the time when i do login the backup is running.
Like 100% of the time when i do login its doing the backup.
Seems like to me when none is online it just doesnt finish the backup.

**Comment by thecybermind** [comment]
This appears to be related to the "only_if_players_online" setting. If no one has been online for at least as long as the "backup_timer", then a backup starts as soon as someone connects.
