### ISSUE TITLE
Not backing up extra files

### ISSUE THREAD

**Issue by Nicon4454** [FTBTeam/FTB-Backups#24]
FTBBackups-1.1.0.1
forge-1.12.2-14.23.5.2847-universal
I have added the following in the extra files section so it will backup all my config files.
`
`#` Add extra files that will be placed in backup _extra_/ folder.
    S:extra_files <
        /home/minecraft/Tigan/config/*
     >
`
if this is the incorrect syntax please let me know. i have been unable to find any documentation on this.

**Comment by batfreak12345678** [comment]
Using 

config/

worked for me after some trial and error.

**Comment by Tealk** [comment]
> Using
> 
> config/
> 
> worked for me after some trial and error.

is the writing correct?
`extra_files = ["config/, server.properties, banned-ips.json, banned-players.json, ops.json, usercache.json, usernamecache.json, whitelist.json"]`
