### ISSUE TITLE
/backup commands do not work [1.16.4]

### ISSUE THREAD

**Issue by Apocryphai** [FTBTeam/FTB-Backups#34]
Running a private server with a custom modpack. None of the listed /backup commands work, all give the error: "Unknown or incompete command".

Have tried /backup start, /backup size and /backup time. Have tried directly in the server console and as op from a game instance.

**Comment by chickenblue** [comment]
I can also confirm.
The in-game notifications do not work properly either.
The output always looks like this: "ftbbackups.lang.timer" "ftbbackups.lang.size.current" and so on.

**Comment by J-Dill** [comment]
Looks like the commands are actually `/ftbbackups ...`

The docs are a little outdated it appears.

**Comment by Apocryphai** [comment]
Confirmed, nice one, thank. Closing :)
