### ISSUE TITLE
Backup Command not working

### ISSUE THREAD

**Issue by Elcar903** [FTBTeam/FTB-Backups#35]
The automatic backup works but not the manual backup.
I have tried using the "/backup start" command and it will not work on 
either my server or single player world.

Forge: 35.1.36
Mod: FTB Backups 2.1.1.6

Thanks

**Comment by Moleculor** [comment]
A brief dig in to the code shows that it looks like they updated the command to be `/ftbbackups` and forgot to update the CurseForge page.

**Comment by Elcar903** [comment]
> 
> 
> A brief dig in to the code shows that it looks like they updated the command to be `/ftbbackups` and forgot to update the CurseForge page.

ok that worked for me. thanks

**Comment by jt-janssen** [comment]
Been looking all over for this, thank you.
