### ISSUE TITLE
FTB Utilities doesn’t always back up the entire world folder

### ISSUE THREAD

**Issue by Dimentive** [FTBTeam/FTB-Backups#9]
FTB Utilities made a backup of my world. My world folder is 14.8 GB large, but the backup is only 10.8 GB large. I checked the `region` folder of both the original world and the backup, and the backup has 928 fewer region files than the original world, so data has been lost.

#### Versions

* **Modpack:** [Enigmatica 2](https://minecraft.curseforge.com/projects/enigmatica2) (version [1.63a](https://minecraft.curseforge.com/projects/enigmatica2/files/2691579))
* **Minecraft:** 1.12.2
* **Forge:** 14.23.5.2781
* **FTB Utilities:** 5.3.0.73
* **FTB Utilities: Backups:** Not installed

**Comment by LatvianModder** [comment]
That's odd, it doesn't check anything in minecraft, it just copies the world folder basically. So everything that was there, should be in backup. Perhaps ran out of storage?

**Comment by Dimentive** [comment]
I have 38 GB on my drive, so it shouldn’t have run out of storage, but considering that this happened, as well as #4, maybe FTB Utilities requires more storage than necessary just in case? I don’t know.
